### ISSUE TITLE
KV: Problem importing in local mode with SvelteKit

### ISSUE THREAD

**Issue by beeb** [vercel/storage#107]
SvelteKit (and Vite) can load environment variables from a `.env` file in development mode. SvelteKit makes those available through `$env/dynamic/private`, `$env/static/private`.

I am adding the `KV_REST_API_URL` and `KV_REST_API_TOKEN` together with my other environment variables inside the `.env` file.

When importing `@vercel/kv`, it assumes that the `KV_REST_API_URL` and `KV_REST_API_TOKEN` are present in the actual environment (through `process.env`).

In dev mode with SvelteKit, these variables are not loaded into the environment, and need to be imported. This creates an error when trying to import `@vercel/kv`. (Missing required environment variables). 

The workaround would be to `import { createClient } from '@vercel/kv'` and manually construct the proxy object, but somehow this also fails with the same environment error:

```ts
import { createClient } from '@vercel/kv'
import { KV_REST_API_TOKEN, KV_REST_API_URL } from '$env/static/private'

const kv = createClient({
	url: KV_REST_API_URL,
	token: KV_REST_API_TOKEN
})
```

**Comment by pdhoward** [comment]
Same error here in dev mode using ts. I also pushed the app to production and encountered same error

The log on createClient returns

ƒ hn(e){return new ln(e)}

which appears to be a function returning the Proxy for VercelKV. In any event, the specific error is

 TypeError: Cannot read properties of undefined (reading 'startsWith')

**Comment by dferber90** [comment]
This seems similar to #99 as sveltekit is also using vite afaik

**Comment by elliott-with-the-longest-name-on-github** [comment]
I didn't write the KV or Edge Config packages, so I don't know what's going on there, but the fix to this is indeed what the original commenter suggested:

```ts
import { createClient } from '@vercel/kv'
import { KV_REST_API_TOKEN, KV_REST_API_URL } from '$env/static/private'

const kv = createClient({
	url: KV_REST_API_URL,
	token: KV_REST_API_TOKEN
})
```

This _should_ provide the values `createClient` needs to initialize correctly, but it seems there's some codepath that's throwing anyway. The general the philosophy should be "The default export uses environment variables so that it's zero-config when possible, but we provide a way to manually construct the client otherwise."

For this specific report, the bug is simple: When we provide the url and token through `createClient`, it shouldn't throw due to a missing var on `process.env`.

**Comment by beeb** [comment]
> I also pushed the app to production and encountered same error

The "zero-config" `import kv from '@vercel/kv'` works for me in production, it's only a problem in local dev mode.

**Comment by dferber90** [comment]
@tcc-sejohnson identified the problem and we're working on a fix <picture data-single-emoji=":thumbs:" title=":thumbs:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..VcBXMJFSW5Dhijgx.-EAtlM54B7kmpit6OHoCdamiG9Ec-D9EjuxG_FxvY1gjBO9r2fmYAZ8g_lWsz-LRIZbL-XeX0nIlNS0_V2i_6THEw_T8RyoG7ogg_JfkkujQmfTpsYTxCQ.lECh7zjM1qtN1xZFZH6XhA" alt=":thumbs:" align="absmiddle"></picture>

**Comment by elliott-with-the-longest-name-on-github** [comment]
This should be fixed by #131.

**Comment by 24jr** [comment]
I'm not clear on this. So it's fixed as of May 18th? I have the same issue I had two weeks ago. Are we supposed to use it differently in localhost? `@vercel/kv": "^0.2.1",`

Actually this now works fine for me with createClient but not shorthand way
```
import { createClient } from "@vercel/kv"
import { KV_REST_API_TOKEN, KV_REST_API_URL } from "$env/static/private"

export const load = async ({ fetch }) => {
  const kv = createClient({
    url: KV_REST_API_URL,
    token: KV_REST_API_TOKEN,
  })
  const kvsetres = await kv.incr("setExample")
  console.log("kvsetres", kvsetres)
```
not
```
// import kv from "@vercel/kv"
export const load = async ({ fetch }) => {
  const kvsetres = await kv.incr("setExample")
```

**Comment by azezsan** [comment]
any updates? I'm still having the same issue

**Comment by igorlanko** [comment]
Just installed it on SvelteKit project and also not able to run it in dev mode. Same thing as OP—only manual client  init with manually imported envs work. Just making sure is this intentional behavior for SvelteKit/Vite? It seems like something was addressed, but I'm not entirely sure if the usage has changed. 

Thanks!
