### ISSUE TITLE
How to Set PostgreSQL Session Variables with @vercel/postgres

### ISSUE THREAD

**Issue by eifo** [vercel/storage#171]
I'm currently trying to set a PostgreSQL session variable in next 13.4.3 using the @vercel/postgres module. I'm trying to use the SET command to set a custom session variable before executing other queries, but I'm encountering an issue.

Here is an example of what I'm trying to do:

const {userId} = auth()
console.log("USERID: ",userId)
await sql`SET request.jwt.claim.uid = ${userId}`;

I'm getting the following error:

error: syntax error at or near "$1"

**Comment by eifo** [comment]
> so got my answer from the neon group, set_config should be used instead as follows:

import {db} from '@vercel/postgres'
const client = await db.connect()
await client.sql`select set_config('auth.uid',${userId},false)`
await client.sql` ...another query`

**Comment by adriancooney** [comment]
Apologies for the delay here @eifo. Glad you got it sorted. To example @eifo's answer a little more, they're acquiring long-lived connection via the `db.connect()` and updating the session. Once you've executed all your statements, be sure to `release` the connection:

```ts
import { db } from '@vercel/postgres'
const client = await db.connect()
await client.sql`select set_config('auth.uid', ${userId}, false)`
await client.sql`...`
client.release()
```

I'm closing out this issue since there is no more action needed. Thanks!
