### ISSUE TITLE
Vercel KV: Intermittent errors of the form "Error [UpstashError]: DB connection refused"

### ISSUE THREAD

**Issue by dkokotov** [vercel/storage#308]
I am using Vercel KV in NextJS `getStaticContext` and `getStaticPaths` to cache Auth0 client credentials grant access tokens (since Auth0 has monthly limits on the number of machine-to-machine tokens per month per account).

The code is very simple, something like this (this is called from `getStaticContext` and `getStaticPaths` to obtain access tokens to use for GraphQL calls):

```
import { kv } from '@vercel/kv';

    async clientCredentialsGrant(scope: string | undefined = undefined) {
        const env = process.env['VERCEL_ENV'] ?? 'development';
        const tokenKvKey = `${env}:m2m-token`;

        const cachedResponse = await kv.get<TokenResponse>(tokenKvKey);
        if (cachedResponse) return cachedResponse;

        const newTokenResponse = await authenticationClient.clientCredentialsGrant({
            audience: process.env['AUTH0_AUDIENCE'] as string,
            scope: scope
        });
        // expire slightly early to avoid racing
        await kv.setex(tokenKvKey, newTokenResponse.expires_in - 60, newTokenResponse);
        return newTokenResponse;
    }
```

Both locally and when deploying to Vercel (I use github actions to run `vercel build` and `vercel deploy` rather than the vercel git integration), I got fairly frequent errors of the form ""Error [UpstashError]: DB connection refused". The error doesn't happen each time, but it happens quite a bit.

**Comment by dkokotov** [comment]
~~After some debugging and trying various workarounds, I found that if I use `createClient` instead of the "pooled" `kv` client, this error does not happen.~~

~~It also never happened if I use REST api directly (eg via CURL).~~ 

~~So it seems like the issue is specifically with the pooled `kv` client instance - though I don't have any theories of what could be the problem.~~

`createClient` and `curl` has the same issue - I just hadn't tried it enough times.

**Comment by adriancooney** [comment]
@dkokotov apologies for the slow reply here - this managed to fly under our radar. It's interesting that you could replicate the issue with `curl` - that eliminates problems with the `@vercel/kv` and a could point to a problem with the database itself. Are you still experiencing this issue with your database? If so, could you open a support ticket with the ID of your team and the ID of your store? We can take it from there.

Since there's no work here, I'm going to close out this issue for now but please feel free to re-open if you suspect an issue with the client.
