### ISSUE TITLE
[Bug report][# pgSQL] Difference on parsing TIMESTAMP between development and Vercel's deployment

### ISSUE THREAD

**Issue by kingwingfly** [vercel/storage#330]
### Summary

The same sql sentence gets different result between localhost and Vercel's deployment.

### Example

See the comment below.

### Steps to Reproduce

I create a table by Vercel's postgreSQL service throught this:

```sql
CREATE TABLE meetings (
    id    SERIAL PRIMARY KEY,
    date_time    TIMESTAMP WITHOUT TIME ZONE
);
```
 Then I insert through this: 
```sql
INSERT INTO meetings (date_time)
VALUES ('2023-08-24 17:00:00');
```
Blow is what the table looks like in Vercel's web query console: 
|id|date_time|
|-|-|
|1|Thu Aug 24 2023 17:00:00 GMT+0800 (中国标准时间)|

Then I query though this:
```sql
SELECT date_time FROM meetings
WHERE id=1;
```

Things goes wrong then:
On my computer localhost, it's:
```
date_time: 2023-08-24T09:00:00.000Z
```
On Vercel, the log shows:
```
date_time: 2023-08-24T17:00:00.000Z,
```
There are 8 hours distance always, how strange.

Here are my query code (looks like no big problem):
```ts
// ...
sql_ = `SELECT meeting_id, date_time, ... WHERE meeting_id IN (SELECT unnest(meetings) FROM users_meetings WHERE id = ${user_id});`;
console.log(sql_);
let meetings = (await client.query(sql_)).rows;
console.log(meetings);
// ...
``` 

The result on Vercel's deployment is right while it's wrong on localhost.

**Comment by kingwingfly** [comment]
repo is here: https://github.com/kingwingfly/meeting-management

**Comment by kingwingfly** [comment]
I solved it for someone‘s telling me `TIMESTAMP WITHOUT TIME ZONE` has nothing to do with the location.

This occurs due to many reasons.

# First
This is what Vercel's **web** console return:

id | date_time
-- | --
1 | Thu Aug 24 2023 17:00:00 GMT+0800 (中国标准时间)

And it is **rendered** from the server through `(new Date('2023-08-24 17:00:00')).toString()`, which transformed according to the session between me and Vercel.

The real return is:
```
verceldb=> select id, date_time as no_tz from meetings;
 id |        no_tz
----+---------------------
  1 | 2023-08-24 17:00:00
```

# Second
Some implicit transforms happened.

`(await client.query(...)).rows` is of type **any[]**. This hides the fact that before `toISOString()` is called implicitly by `console.log()`, `rows[0].date_time` is actually already of type `Date` because `new Date(date_time_string)` has been called  implicitly.

The `date_time_string`(`2023-08-24 17:00:00`) having no time zone included, will be considered as a local time, and `toISOString()` during `console.log()` will lead to time zone transforming.

Here's an example:
```ts
// My computer is UTC+8

let t = new Date("2023-08-25 12:00:00"); // no time zone
console.log("without tz ISO:", t.toISOString());
// without tz ISO: 2023-08-25T04:00:00.000Z
console.log("without tz Local:", t.toLocaleString());
// without tz Local: 2023/8/25 12:00:00
t = new Date("2023-08-25 12:00:00+00"); // 'UTC' time zone
console.log("with tz ISO:", t.toISOString());
// with tz ISO: 2023-08-25T12:00:00.000Z
console.log("with tz Local:", t.toLocaleString());
// with tz Local: 2023/8/25 20:00:00
```

The two ISO outputs are exactly 8 hours away.

# Infer
Above all, we can infer:
1. Database's return is the same, which is UTC time but without timezone mark `+00`
2. On dev, it's considered as time_string without `+00`; On server, it's consider as time_string with `+00`.

# Verify
The data:
```
select * from meetings;
meeting_id |      date_time      
------------+--------------------
         16 | 2023-08-25 03:00:00
```
## On dev
Let's print the query result, `console.log(rows)`:
```
[
  {
    meeting_id: 16,
    date_time: 2023-08-24T19:00:00.000Z
  }
]
```
$24 - 19 + 3 = 8$，8 hours before 2023-08-25 03:00:00.
Fit in our guess.

## On server
Let's deploy it on Vercel and check the logs:
```
[
  {
    meeting_id: 16,
    date_time: 2023-08-25T03:00:00.000Z
  }
]
```
Difference appears.

By the way, if I do this:
```sh
npm run build
npm run start
```
The result is the same as that of the development.


# Conclusion
Above all, differences exist between deployment and development at the implement of "@vercel/postgres" package.
My version is `"@vercel/postgres": "^0.4.1",`.
And I know this package is used for Vercel, maybe there are differences between running on my computer and running on Vercel's servers. It may parse the result of the sql sentence in different ways on my side and Vercel's server side. By the way, the deployment's date_time is right.

So, is the difference really exist?
And how do you think of this guess.

# Solution
I solved by modifying the sql sentence.
```
SELECT id, date_time AT TIME ZONE 'UTC' AS utc_date_time FROM meetings;
```
Which returns time_string with time zone mark like `2023-08-25 03:00:00+00`.

And both my computer and Vercel's deploy environment can handle it correctly and the same.

**Comment by cvanem** [comment]
**EDIT: A better solution was found:**

Edge Function: `sql'SELECT created AT TIME ZONE 'UTC' AS created, updated AT TIME ZONE 'UTC' AS updated FROM users;'`
JS Client: `const localDate = new Date(date).toLocaleString();`


-------------------------------------------------------------

@kingwingfly I encountered what I think is the same or similar issue.  In my testing, I found that the @vercel/postgres library was automatically adjusting the timestamp value from the postgres database to the server's local time.  This is similar to how the [node-postgres library works](https://node-postgres.com/features/types#date--timestamp--timestamptz).  The problem is that the adjustment was done in the wrong way.  For the adjustment to be correct, it should have been subtracting 6 hours, but it was adding six hours.  In my opinion, the library shouldn't be doing any adjustments at all and just deliver the UTC ISO string to the client.

Timestamp in DB:        2023-09-09 17:05:29.843126 +00:00  (When viewed with DataGrip tool)
Timestamp after calling @vercel/postgres using sql on a server edge function: 2023-09-09T23:05:29.843Z

My time zone is UTC - 6 hours, so not sure why the library is adding 6 hours to the database timestamp value, unless maybe it thinks it is stored in the database as a local time zone and not UTC.

**The Expected Behavior**
-----------------------
In my experience the best and expected behavior would be to store all timestamps in the database as UTC, don't do any type of automatic conversions in database library and then adjust the UTC time for display in the user's browser with respect to their local time zone.

**The Fix**
-----------------------
To fix the the problem, I adjust the times back to UTC time on the server, and then in the client I convert the times to the user's local time.  This results in correct time display using both development and production environments, with different server time zones.  Here is some sample code:

Server Edge Function:

```
import { sql } from '@vercel/postgres';

export const config = {
  runtime: 'edge',
  regions: ['iad1'], // only execute this function on iad1
};

const isEmpty = (str: any) => !str || 0 === str.length;

const fixDates = ({ rows = [], keys = [] as string[] }) => {
  var offsetMinutes = new Date().getTimezoneOffset();
  rows.forEach((row: any) => {
    keys.forEach((k) => {
      if (!isEmpty(row[k])) {
        var date = new Date(row[k]);
        const adjustedDate = new Date(0);
        adjustedDate.setUTCMilliseconds(date.getTime() - offsetMinutes * 60000); // Reverse the timezone adjustment
        row[k] = adjustedDate.toISOString();
      }
    });
  });
};

const handler = async (req) => {
  await sql`CREATE TABLE IF NOT EXISTS test (created TIMESTAMP DEFAULT (now()), updated TIMESTAMP);`;
  await sql`INSERT INTO test (updated) VALUES (${new Date(Date.now()).toISOString()});`;

  var data = await sql`SELECT * FROM test`;

  var { rows } = data as any;
  fixDates({ rows, keys: ['created', 'updated'] });

  return new Response(JSON.stringify(rows), {
    status: 200,
    headers: { 'Content-Type': 'application/json' },
  });
};

export default handler;
```



Client:

```
const isEmpty = (str: any) => !str || 0 === str.length;
const convertSqlDateTimeUtc = (serverDate) => (isEmpty(serverDate) ? serverDate : new Date(serverDate).toLocaleString());
```

**Comment by kingwingfly** [comment]
> @kingwingfly I encountered what I think is the same or similar issue. In my testing, I found that the @vercel/postgres library was automatically adjusting the timestamp value from the postgres database to the server's local time. This is similar to how the [node-postgres library works](https://node-postgres.com/features/types#date--timestamp--timestamptz). The problem is that the adjustment was done in the wrong way. For the adjustment to be correct, it should have been subtracting 6 hours, but it was adding six hours. In my opinion, the library shouldn't be doing any adjustments at all and just deliver the UTC ISO string to the client.
> 
> Timestamp in DB: 2023-09-09 17:05:29.843126 +00:00 (When viewed with DataGrip tool) Timestamp after calling @vercel/postgres using sql on a server edge function: 2023-09-09T23:05:29.843Z
> 
> My time zone is UTC - 6 hours, so not sure why the library is adding 6 hours to the database timestamp value, unless maybe it thinks it is stored in the database as a local time zone and not UTC.
> 
> ## **The Expected Behavior**
> In my experience the best and expected behavior would be to store all timestamps in the database as UTC, don't do any type of automatic conversions in database library and then adjust the UTC time for display in the user's browser with respect to their local time zone.
> 
> ## **The Fix**
> To fix the the problem, I adjust the times back to UTC time on the server, and then in the client I convert the times to the user's local time. This results in correct time display using both development and production environments, with different server time zones. Here is some sample code:
> 
> Server Edge Function:
> 
> ```
> import { sql } from '@vercel/postgres';
> 
> export const config = {
>   runtime: 'edge',
>   regions: ['iad1'], // only execute this function on iad1
> };
> 
> const isEmpty = (str: any) => !str || 0 === str.length;
> 
> const fixDates = ({ rows = [], keys = [] as string[] }) => {
>   var offsetMinutes = new Date().getTimezoneOffset();
>   rows.forEach((row: any) => {
>     keys.forEach((k) => {
>       if (!isEmpty(row[k])) {
>         var date = new Date(row[k]);
>         const adjustedDate = new Date(0);
>         adjustedDate.setUTCMilliseconds(date.getTime() - offsetMinutes * 60000); // Reverse the timezone adjustment
>         row[k] = adjustedDate.toISOString();
>       }
>     });
>   });
> };
> 
> const handler = async (req) => {
>   await sql`CREATE TABLE IF NOT EXISTS test (created TIMESTAMP DEFAULT (now()), updated TIMESTAMP);`;
>   await sql`INSERT INTO test (updated) VALUES (${new Date(Date.now()).toISOString()});`;
> 
>   var data = await sql`SELECT * FROM test`;
> 
>   var { rows } = data as any;
>   fixDates({ rows, keys: ['created', 'updated'] });
> 
>   return new Response(JSON.stringify(rows), {
>     status: 200,
>     headers: { 'Content-Type': 'application/json' },
>   });
> };
> 
> export default handler;
> ```
> 
> Client:
> 
> ```
> const isEmpty = (str: any) => !str || 0 === str.length;
> const convertSqlDateTimeUtc = (serverDate) => (isEmpty(serverDate) ? serverDate : new Date(serverDate).toLocaleString());
> ```

Hey, I agree that this library treats localhost and non-localhost differently. 

And you can easily avoid it by adding `AT ZONE 'UTC'` when querying, like this:
```sql
SELECT id, date_time AT TIME ZONE 'UTC' AS utc_date_time FROM meetings;
```
The library will treat this sql sentence's returning in the same and right way.

Lastly, I found this may be not due to vercel's implement but one of the `vercel/postgres`' dependence called `neondatabase/serverless`

**Comment by cvanem** [comment]
> And you can easily avoid it by adding AT ZONE 'UTC' when querying, like this: 
SELECT id, date_time AT ZONE 'UTC' AS utc_date_time FROM meetings;

@kingwingfly 

I can confirm that `AT TIME ZONE 'UTC'` works and is a better solution.  I think it would be nice if the `@postgres/sql` library contained a global setting so you could select all timestamps with `AT TIME ZONE 'UTC'` by default.

Note:  `AT ZONE 'UTC'` as you referenced throws a syntax error for me.

Working example:  

`SELECT created AT TIME ZONE 'UTC' AS created, updated AT TIME ZONE 'UTC' AS updated FROM users`

**Comment by adriancooney** [comment]
Thanks for the great write ups here folks. I've done some digging into this myself and it seems like these are some options.  There are three timezones in play: the "database timezone" (i.e. Postgres), the "server timezone" (i.e. Vercel or your local machine) and the "stored timezone" (the timezone associated with the stored value e.g. `2023-08-25T03:00:00Z` is UTC).

1. If your timestamp has a type in Postgres of `::timestamp` or `::timestamp without time zone`, your timestamp will use the "stored timezone" in Postgres and be deserialized to the "server timezone" in the server (i.e. lose the "stored timezone"). This is because the `::timestamp` does not return timezone information so the server uses it's own.
2. If your timestamp has a type in Postgres of `::timestamp with time zone`, your timestamp will use the "stored timezone" in Postgres and be deserialized to the "stored timezone" (i.e. retain timezone information) in the server. This is because the `::timestamp with time zone` always returns timezone information and the server correctly uses it when parsing the date.
2.a. When inserting the timestamp into the database, if it does not explicitly set a timezone (e.g. `2023-08-25 03:00:00`), it will use the "database timezone".

You can also explicitly set the timezone of the timestamp using the `at time zone 'UTC'`, like you are above. If you want to avoid doing this in every query, you should store your timestamps as `::timestamp with time zone` and *always* insert your timestamps with a UTC time zone (e.g. `2023-08-25 03:00:00+00` or `2023-08-25T03:00:00Z` ISO8601). This will force Postgres to always return the timezone to the server (e.g. `2023-08-25 03:00:00+00`) and the server to always deserialize it as UTC.

I don't think there's any behaviour changes needed in the client here, it's doing it's best with Javascript's awful Date implementation. Given that, I'm going to close out this issue. Thanks for the help!

**Comment by kingwingfly** [comment]
> Thanks for the great write ups here folks. I've done some digging into this myself and it seems like these are some options.  There are three timezones in play: the "database timezone" (i.e. Postgres), the "server timezone" (i.e. Vercel or your local machine) and the "stored timezone" (the timezone associated with the stored value e.g. `2023-08-25T03:00:00Z` is UTC).
> 
> 
> 
> 1. If your timestamp has a type in Postgres of `::timestamp` or `::timestamp without time zone`, your timestamp will use the "stored timezone" in Postgres and be deserialized to the "server timezone" in the server (i.e. lose the "stored timezone"). This is because the `::timestamp` does not return timezone information so the server uses it's own.
> 
> 2. If your timestamp has a type in Postgres of `::timestamp with time zone`, your timestamp will use the "stored timezone" in Postgres and be deserialized to the "stored timezone" (i.e. retain timezone information) in the server. This is because the `::timestamp with time zone` always returns timezone information and the server correctly uses it when parsing the date.
> 
> 2.a. When inserting the timestamp into the database, if it does not explicitly set a timezone (e.g. `2023-08-25 03:00:00`), it will use the "database timezone".
> 
> 
> 
> You can also explicitly set the timezone of the timestamp using the `at time zone 'UTC'`, like you are above. If you want to avoid doing this in every query, you should store your timestamps as `::timestamp with time zone` and *always* insert your timestamps with a UTC time zone (e.g. `2023-08-25 03:00:00+00` or `2023-08-25T03:00:00Z` ISO8601). This will force Postgres to always return the timezone to the server (e.g. `2023-08-25 03:00:00+00`) and the server to always deserialize it as UTC.
> 
> 
> 
> I don't think there's any behaviour changes needed in the client here, it's doing it's best with Javascript's awful Date implementation. Given that, I'm going to close out this issue. Thanks for the help!

Thanks a lot! Your explanation is so good, and your suggestion is absolutely the best solution. 

It's hard for me to express my opinion in English maybe 😭, but the following discussion may still point out a potential problem.

If we all store and load timestamp in UTC, then it can be seen as just a string with 'WITHOUT TIME ZONE', things will become much easier, although this will cause the server not knowing the correct time zone and we need some changes finally.

Due to that we created the table with 'date_time TIMESTAMP WITHOUT TIME ZONE', and we usually store timestamp in UTC, then database always returns a time string **without** time zone marker.

The problem is that, although the database returns the same result(string without time zone marker), the library considers it as string without marker on localhost while considering it as a string with +00 marker on non-localhost. This leads a difference that is not reasonable.

For example, I am a coding rookie not knowing the pgsql timestamp can store time zone information and decide to store all timestamps in UTC manually, and convert them when needed, so I do not need think too much. This is quite simple. After search in Baidu, a Chinese search engine, it suggests using 'TIMESTAMP WITHOUT TIME ZONE'. Then, I do a query, and the library returns a Date. However, on localhost, database's return is considered as a local time string, but on non-localhost, it is considered as a UTC time string, then things go wrong. The same input, but the different output, too confused. 

Now I know that always store timestamps with time zone is a better solution, however, storing shorter timestamp without time zone as default is not too bad if all coders know all timestamps are in UTC. And it's may exactly why 'TIMESTAMP WITHOUT TIME ZONE' exists. But the difference exists between localhost and non-localhost, 🤔.
