### ISSUE TITLE
Purely numeric string comparisons will get false

### ISSUE THREAD

**Issue by moondie** [vercel/storage#350]
I compare the password entered by the user (which I'm sure is of type string) with the password obtained by querying KV, if the password is a normal string, the comparison result is normal, while if the password is a plain number, then the comparison result will be false.

my code:
```javascript
interface userdata {
  [key: string]: unknown;
  password: string;
  balance: number;
}
 const fields = ["password", "balance"];
  const getdata = await kv.hmget<userdata>(username, ...fields);
if (!getdata || getdata?.password !== password) {  // will be false
    response = NextResponse.json(
      {
        error: true,
        msg: "username or password error",
      },
      {
        status: 401,
      },
    );
  }```

**Comment by moondie** [comment]
Even with the declaration "
```javascript
interface userdata {
  [key: string]: unknown;
  password: string;
  balance: number;
}
```
" , the type of getdata?.password is still Number.

**Comment by adriancooney** [comment]
Hi @moondie. The default `kv` client has `automaticDeserialization` set to `true` which means it will try to deserialize all string values it receives. In this case it sees a number string and deserializes it a number. I can see how this can be confusing but it is expected behaviour. You can disable `automaticDeserialization` like so:

```js
import { kv, createClient } from '@vercel/kv';

const customKvClient = createClient({
  url: process.env.KV_REST_API_URL,
  token: process.env.KV_REST_API_TOKEN,
  automaticDeserialization: false,
});

await customKvClient.set('password', 1);

console.log(await kv.get('password')); // 1
console.log(await customKvClient.get('password')); // '1'
```

You can read more about [`automaticDeserilaization` on the README](https://github.com/vercel/storage/tree/main/packages/kv#automatic-deserialization).
