### ISSUE TITLE
edge-config not working in react-native: ...this package itself specifies a `main` module field that could not be resolved

### ISSUE THREAD

**Issue by tobbbe** [vercel/storage#357]
Trying to run edge-config in react-native but it doesnt work. Getting this error. Running rn 0.67.4. Is it fixable? 😃

```
Error: While trying to resolve module `@vercel/edge-config-fs` from file `/Users/tobbe/dev/appppp/node_modules/@vercel/edge-config/dist/index.js`, the package `/Users/tobbe/dev/appppp/node_modules/
@vercel/edge-config-fs/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved
```

**Comment by dferber90** [comment]
Could you share a bit more about your use case? I'm wondering why you'd include the edge config sdk in what seems to be a client bundle?

**Comment by tobbbe** [comment]
I thought I was supposed to use the client to read the values. But I guess you mean I should setup a http endpoint that uses the client, which I then call from my app? 😊
When reading the docs for edge-config that's a bit unclear imo.

**Comment by dferber90** [comment]
The benefit of Edge Config is that it is extremely fast to read from your deployment on Vercel. So you would usually have API Routes which use the Edge Config SDK (the `@vercel/edge-config` package) to read Edge Config on your server. You can then return an API response.

There might be some cases where you want to read Edge Config directly from a client, but this is usually not great since it forces you to leak the Edge Config's read-only token to the client which essentially makes all content of your Edge Config public.

I therefore recommend creating an API endpoint in your application and only forwarding the specific data you are interested in. You can create an Edge API Route so that your endpoint is globally distributed, which lowers latency.

**Comment by tobbbe** [comment]
Okey! Thanks for the clarification!
