### ISSUE TITLE
Issues with Django Session and Admin Interface on Vercel Deployment

### ISSUE THREAD

**Issue by Raztsook** [vercel/storage#358]
Hello everyone,

I recently deployed my first Django application on Vercel. While the app is live and most functionalities are working as expected, I've encountered a couple of challenges:

Django Session Issue: One of my functions utilizes Django's session, but lately, Vercel doesn't seem to recognize the session table. I've attached a screenshot for reference. If anyone has faced a similar issue or is familiar with this problem, I'd greatly appreciate some guidance on how to resolve it.
![image](https://github.com/vercel/storage/assets/95634001/f894e6e3-16cf-474f-8eae-8e4ef7f1a821)

Django Admin Interface: Locally, I can access and use Django's admin interface without any hitches. However, post-deployment on Vercel, I'm unable to connect to the admin interface. It appears that the platform doesn't recognize the table associated with the admin interface.
![image](https://github.com/vercel/storage/assets/95634001/ccc33ad1-90ae-4860-9ee2-241244f44d7c)

I'm relatively new to deploying Django apps, especially on Vercel, so any insights, suggestions, or solutions would be immensely helpful.

Thank you in advance for your assistance!

**Comment by adriancooney** [comment]
@Raztsook general support queries like this are better suited to the [Help category in Vercel's Discussions](https://github.com/orgs/vercel/discussions/categories/help).

It looks like your application is erroring because the tables it expects do not exist. Here are some things you can do:

* Open a direct connection to your Vercel Postgres database via `psql` and run the `\d` command. It will list the tables in your database. Double check `auth_user` and `django_session` exist. To connect via `psql`, follow the instructions on your database on the Vercel Dashboard.
* If the tables exist in your Vercel Postgres database, validate your production application is connecting to it correctly by ensuring the connection details it is using point to your Vercel Postgres database.
* If the tables don't exist and you are correctly connecting to your Vercel Postgres database from your production application, ensure that you have run your migrations to create the tables.

Since there is no bug report or work to do here, I'm going to close out this issue. Please feel free to reach out to our support if you need more help.
