### ISSUE TITLE
vercel/postgres sql POSTGRES_URL not found

### ISSUE THREAD

**Issue by PaulieScanlon** [vercel/storage#364]
Hi team, i was trying to use @vercel/postgres with Edge Functions in an Astro project. I hit a stumbling block when doing the following:

```
import { sql } from '@vercel/postgres';

export async function GET() {
  const response = await sql`SELECT * FROM table_name`;

  return new Response(
    JSON.stringify({
      message: 'A Ok!',
      response: response,
    })
  );
}
```

Which gives me the error: 
```
VercelPostgresError - 'missing_connection_string': You did not supply a 'connectionString' and no 'POSTGRES_URL' env var was found.
```

I understand this is because Astro uses Vite and Vite doesn't expose environment variables to `process.env`

The work around i'm currently using involves using `createPool` instead of `sql` from @vercel/postgres.

```
import { createPool } from '@vercel/postgres';

export async function GET() {
  const pool = createPool({
    connectionString: import.meta.env.POSTGRES_URL,
  });
  const response = await pool.sql`SELECT * FROM table_name`;

  return new Response(
    JSON.stringify({
      message: 'A Ok!',
      response: response.rows,
    })
  );
}
```

This works (i think) because i'm able to provide a value for `connectionString` by accessing the environment variables in Astro using: `import.meta.env.POSTGRES_URL`

I was wondering if there's a way to use `sql` and provide a config option to override the `connectionString`?

Something like this would be kinda handy. 

```
import { sql } from '@vercel/postgres';

export async function GET() {
  const db = sql(import.meta.env.POSTGRES_URL);

  const response = await db`SELECT * FROM table_name`;

  return new Response(
    JSON.stringify({
      message: 'A Ok!',
      response: response,
    })
  );
}
```

**Comment by adriancooney** [comment]
Hi @PaulieScanlon! Nice to meet another from Neon. Thanks for opening the issue and your suggestion. You are correct, the way Vite handles env vars prevents us from implicitly using the connection string from the environment. Unfortunately I don't see us implementing this suggestion in the near term for two reasons:

* As you've explained, we already have the `createClient` method which implements this behaviour - the only difference being the function name and signature. Have you considered exporting the client from another file and importing it that way? This feels like a reasonable compromise and improvement in DX.

```ts
export const db = createClient({
  connectionString: import.meta.env.POSTGRES_URL
})
```

* It complicates the `sql` function signature and might create confusion among developers in how the function is called (e.g. typings).

We can of course reconsider this in the future if there's enough of a response from the community. Since there is no work to be done here, I'm going to close out this issue. Please feel free to re-open if necessary.

**Comment by PaulieScanlon** [comment]
Hey @adriancooney thanks for the reply. No worries at all. 

I hadn't tried the `createClient` export to be honest. That's probably a better solution that what i've been using, which was using the `createPool` export. 

... and yeah, no worries, probably unnecessary work. 

Perhaps one for the docs team but, it might be worth mentioning this as a solution because it tripped me up. I don't know how many folks are using Astro / Vite to build stuff with vercel/postgres, curse my wretched luck, i should just stick to using Next.js hey! :)
