### ISSUE TITLE
Docs Typo: blob server upload

### ISSUE THREAD

**Issue by RatulMaharaj** [vercel/storage#392]
Hi there 👋

I found a small typo in the vercel blob storage docs in the [Create a server upload page](https://vercel.com/docs/storage/vercel-blob/quickstart#create-a-server-upload-page) section.

---

**Here's the typo**
```ts
const newblob = (await response.json()) as PutBlobResult;

setBlob(newBlob);
```

**This would be the fix**
```ts
const newBlob = (await response.json()) as PutBlobResult;

setBlob(newBlob);
```

To reiterate, the typo lies in the difference between `newBlob` and `newblob`. 

---

PS: Would gladly open a PR, but wasn't able to find where the docs lived.

**Comment by dferber90** [comment]
Thanks for reporting! The docs live in an internal repo, that's why you could not find them :) I've opened a PR to fix, which should go out later today <picture data-single-emoji=":blob_thanks:" title=":blob_thanks:"><img class="emoji" width="20" height="auto" src="https://single-emoji.vercel.app/api/emoji/eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..TmPEoqWhuThHlkQq.Gwnp4P1IiZgd48JSjPZCnhJbEryRMPWjavAbK7L6p77cAGOcPscO9bX0Oc9OUjvKvBsKNc2JLYJlr46gkPlOHjHLeDfuy44jr4eeQZmCdQRWomzMpcjTBnlxEC47.25W85nN79Ie7q3azYvjWeA" alt=":blob_thanks:" align="absmiddle"></picture>

**Comment by vvo** [comment]
Thank you @dferber90
