### ISSUE TITLE
Add the ability to get the latest updatedAt first in the https://vercel.com/docs/storage/vercel-blob/using-blob-sdk#list method

### ISSUE THREAD

**Issue by kumardeepam** [vercel/storage#533]
Add an option to get the latest updated blobs first in the list() method.
It will help to get lates blobs first when using the pagination.

**Comment by vvo** [comment]
Hey Kumar, we can't and won't be able to provide a list() method that can sort by updated-at date. Because of the underlying object storage technology we use doesn't have this feature (and most of them don't: aws s3 doesn't have it)

Blobs are always sorted alphabetically, and if you deeply need this sort by update feature then your best bet would be to name your blobs this way: `2023-11-02T20:05:00-blob.txt`.

This way you will be able to list the recently updated files first. Hope this works for you.

**Comment by kumardeepam** [comment]
@vvo Hi Vincent, will try this method out or maybe will store the reference to mongodb and get my sorted list from there which i was planning to eventually. 
Thank you for the prompt guidance on this.
