### ISSUE TITLE
Intermittent Request Failures with Vercel Postgres and Next.js

### ISSUE THREAD

**Issue by JuanSpada** [vercel/storage#554]
Hello,

I am experiencing intermittent issues with Vercel Postgres when making requests from a Next.js application. The behavior is inconsistent: sometimes the requests work as expected, but other times they fail without any clear reason.

- **Consistent Direct Database Queries:** When I execute queries directly in the database, they always work without any issues.
- **Inconsistent Behavior in Next.js:** However, when making the same queries from my Next.js application, the results are unpredictable. Sometimes they succeed, and other times they fail.

This inconsistent behavior is challenging to debug, as there are no apparent errors or patterns to these failures. I am looking for any guidance or suggestions on how to resolve or further diagnose this issue.

This request sometimes works and sometines doesnt, I dont receive any error messages.

```
"use server";

import { sql } from "@vercel/postgres";

export async function abrirConversacion(conversacionId) {
  try {
    const resultado = await sql`
      UPDATE conversaciones SET estado = 'abierto' WHERE id = ${conversacionId};
    `;
    console.log("Resultado de la consulta:", resultado);
    return true;
  } catch (error) {
    console.error("Error en abrirConversacion:", error);
    return false;
  }
}
```

On the next component:

```
import { abrirConversacion } from "@/lib/data";

const handleAbrirConversacion = async () => {


    setLoading(true);
    try {
      await abrirConversacion(convId);
      setEstado("abierto");
    } catch (error) {
      console.error(`Error al abrir la conversación: ${error}`);
    }
    setLoading(false);
    setOpen(false);
  };

```
Thank you for your assistance.

**Comment by MikeG112** [comment]
I've had the same issue. I haven't been able to reproduce the situation deterministically yet, but in my case it only occurs with `UPDATE` statements, so might be something to that detail.

**Comment by MikeG112** [comment]
In case it's useful, I was able to deterministically reproduce and resolve my issue with the aid of a fact I didn't know was true of NextJS:

"fetch requests that use the POST method are also automatically cached. Unless it's inside a [Route Handler](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) that uses the POST method, then it will not be cached." (source: [Next Docs](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#caching-data))

I had assumed POST requests would not be cached, but it turns out they are generally cached in [Server Actions](https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-components), just not in [Route Handlers](https://nextjs.org/docs/app/building-your-application/routing/route-handlers). I was using a Server Action for POST/PUT requests, and the cache was leading to the unexpected behavior.

I was able to use [revalidatePath](https://nextjs.org/docs/app/api-reference/functions/revalidatePath) while leaving my implementation in a non-Route-Handler Server Action to get the desired behavior. Alternatively, it seems you can move to a Route Handler pattern.

Hope this might be relevant to your issue too.

**Comment by luismeyer** [comment]
hey @JuanSpada,
did the above answer solve this issue for you? In case this is a Next caching problem you can also call `unstable_noStore` ([docs](https://nextjs.org/docs/app/api-reference/functions/unstable_noStore)) in your action to opt out of the fetchCache.

**Comment by luismeyer** [comment]
also if you still have the issue it would be great to get a minimal reproduction of the issue. Something like
1. create new next-app
2. do this
3. do that

**Comment by luismeyer** [comment]
I'll close this due to inactivity. Feel free to reopen

**Comment by JuanSpada** [comment]
Fix it with unstable_noStore and revalidateTag(), Thank you!
