### ISSUE TITLE
[vercel/blob] file should use the true mime type when uploading the file

### ISSUE THREAD

**Issue by mfts** [vercel/storage#569]
So I just came across a issue where I'm letting users upload their own images. I'll preview them before uploading to blob storage. 

To preview them I'm creating a base64 `dataUrl` from the image using `FileReader`. 

```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAACVAAAAW0CAYAAAAqsbobAAAMQGlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnluSkEBooUsJvQkiUgJICaGF3hFEJSQBQokxEFTs6KKCaxcRsKGrIgpWQCwoolhYFHtfLCgo62LBrrxJAui6r3zvfN ...
```

_Side Quest: I'd love to upload a dataUrl straight to vercel/blob, currently that doesn't work_

Anyways, so I'm converting it to a `File` blob before uploading. 

```ts
const dataURLtoFile = ({
    dataUrl,
    filename = "logo.png",
  }: {
    dataUrl: string;
    filename?: string;
  }) => {
    let arr = dataUrl.split(","),
      match = arr[0].match(/:(.*?);/),
      mime = match ? match[1] : "",
      bstr = atob(arr[1]),
      n = bstr.length,
      u8arr = new Uint8Array(n);

    while (n--) {
      u8arr[n] = bstr.charCodeAt(n);
    }

    return new File([u8arr], filename, { type: mime });
  };
 ``` 

However, a File requires a `filename`. It doesn't specifically state that the `filename` has to include the extension. It's just common convention. 

However, the `File` fails to upload to vercel/blob if the filename doesn't include an extension.

```ts
const uploadImage = async (file: File) => {
    const newBlob = await upload(file.name, file, {
      access: "public",
      handleUploadUrl: "/api/file/logo-upload",
    });

    return newBlob.url;
 };
```

I'm giving it a name `logo.png` but of course the mime type could also be a `image/gif` or `image/jpeg`.

So no matter what image I upload, if the filename is `logo.png`, it will upload to vercel blob and use the `.png` extension as the extension in the blob url 

```
https://36so9a8uzykxknsu.public.blob.vercel-storage.com/logo-<RANDOM-ID>.png
```

Technically the file when downloaded is still the original mime type. but the extension will be `png`. 

I'm providing the true `mime type` in the `File` object. I'd love to use it in vercel/blob and not have to rely on a file extension alone.

**Comment by vvo** [comment]
Hi @mfts! Thanks for the question here.

Before diving into details, I want to give a way to solve your issue right now:
1. If you have the real mime type of the image, then you could use a library. Example: https://github.com/jshttp/mime-types?tab=readme-ov-file#mimeextensiontype
2. Once you have that, you can add it back to the filename and done

Now, you may not want to have an extension at all. Although, careful because then if a customer downloads your file, then their system won't be able to display the image properly (as a file should have an extension for that).

Is that a requirement from your usecase to NOT have file extensions?

Side question: if you have an `<input />`, why do the File => dataUrl => File change when you could just provide the File to the npm package directly? Previewing the file as a dataUrl shouldn't prevent you to upload it as the real File from the customer.

Happy to learn more here!

**Comment by mfts** [comment]
> 1. If you have the real mime type of the image, then you could use a library. Example: https://github.com/jshttp/mime-types?tab=readme-ov-file#mimeextensiontype
> 2. Once you have that, you can add it back to the filename and done

Thanks, that's very handy!

> Is that a requirement from your usecase to NOT have file extensions?

No it's not and with the above extension type it will solve the issue. 

> Previewing the file as a dataUrl shouldn't prevent you to upload it as the real File from the customer.

Correct, it doesn't prevent me from uploading the `File`. I just need to keep track of two variables in state instead of one (dataUrl) and move them around my components. I guess it's more a me-problem then a blob-problem. 

Thanks for helping out! Will add the mime extension and refactor some of the component to make it easier for me

**Comment by vvo** [comment]
Awesome 👍 Also, uploading a file as dataUrl could mean the upload would take a lot longer, perhaps because the format is no more binary (we could always turn it back to a Blob yep).

Closing for now then 👍
