### ISSUE TITLE
[blob] `downloadUrl` with additional expiration token or stream 

### ISSUE THREAD

**Issue by mfts** [vercel/storage#594]
I have a use case where I don't want to expose/provide the `downloadUrl` to the client. Always inspectable from the network panel. 

In Papermark, when someone views a 10-page document, it's actually split up into into 10 individual blobs. However, the sender can enable the viewer to download the file. Then I fetch the 10-page document as a single blob and provide the `downloadUrl`. 

However, now the downloadUrl is always available on this url, forever (until the blob is deleted). 

I understand that once a file is downloaded, then technically it can be uploaded anywhere else and lives on forever. But I kind of want to prevent the case that a downloadUrl exists. In general, I want to prevent any direct link to the blob url of the 10-page document. 

I understand this is a niche case specific to me. I was trying to stream the file from the downloadUrl to the client but once the file is bigger than 4MB, the function complains that it's too big. 

I guess what I'm imagining is an obfuscated url with an `expirationToken` (signed Urls, maybe?).

**Comment by vvo** [comment]
Hey, @mfts, thank you for the explanation; from what I understand, what you're looking at would be signed URLs since they have a built-in expiration. This doesn't yet exists on Vercel Blob.

As an immediate solution, have you tried to create an edge function that would do something like:
```
return new Response(fetch('blob url'));
```

Streaming (rewriting) the blob URL should work, but it probably needs to be an edge function, not a serverless one. Another way maybe would be to use https://nextjs.org/docs/app/api-reference/functions/next-response#rewrite. As long as you're able to generate na encrypted value in the url and decrypt it yourself you could do so (https://github.com/vvo/iron-session?tab=readme-ov-file#sealdatadata-unknown--password-ttl--promisestring can do that :D).

As for the Vercel Blob feature. Yes, we would like to build it, and having you requiring it is a good indicator we should do it soon. I've called it "temporary URLs, " which would be very similar to signed URLs.

I can't provide any ETA yet though so hopefully the rewrite solution can work for you for now.

**Comment by mfts** [comment]
Thanks @vvo - very helpful and actionable answer as usual. 

I like the idea of the rewrite. Didn't think that would be possible but good idea. 

I like temporary urls and happy to give feedback on any early prototypes when you're ready :)

**Comment by vvo** [comment]
Closing as this is a feature request we will investigate and report back

**Comment by wilson090** [comment]
Hey @vvo any update on when this feature might ship? We need this to prevent abuse patterns on our site and will need to switch to R2 if we can't implement this via vercel

**Comment by vvo** [comment]
@wilson090 While we do not have a NATIVE way to do this, now that private blobs are available (https://vercel.com/docs/vercel-blob/private-storage) you can definitely implement:
- one time access to files
- expiration based access to files

Since private blob urls cannot be accessed by default, since you have to proxy them through your endpoints, you can implement whatever delivery strategy you need.

We will provide a native way to achieve this at some point.
