### ISSUE TITLE
`@vercel/edge-config` still breaks even if `@opentelemetry/api` is marked as peer deps

### ISSUE THREAD

**Issue by grikomsn** [vercel/storage#611]
Continuing from #606 and #607, `@vercel/edge-config` still breaks even if `@opentelemetry/api` is marked as peer deps: https://vercel.com/grikomsn/roe/HZvq2b5jhhSTWaXNwGaBKUeDYbQS#L23-L24

![CleanShot 2024-02-18 at 05 30 19@2x](https://github.com/vercel/storage/assets/8220954/8e5bb8b9-2a0d-4f2f-b3f0-bed3951d01c4)

One "fix" is to stub and override `@opentelemetry/api` with an empty object/function, which I tested and works: https://github.com/grikomsn/roe/commit/da7a36cde2d284c56e2bcb2f1435e875ccedb40f

```js
exports.trace = {
  getTracer() {
    return null;
  },
};
```

As a general fix, I don't know the best way moving forward. Opening this issue for visibility and point of discussion.

**Comment by dferber90** [comment]
It looks like there's no great way for us to make `@opentelemetry/api` truly optional without introducing other tradeoffs. So we will likely revert the change to `peerDependenciesMeta`.

I noticed that in your project's pnpm-lock you've explicitly set `autoInstallPeers: false` which is probably why you're running into this issue. Could you try removing that setting?

**Comment by grikomsn** [comment]
Even without that setting it still fails, see previous commits and status checks.

**Comment by AndyBitz** [comment]
It does appear that `pnpm` and `yarn` do not install `peerDependencies`, unlike `npm`.

Marking it as optional won't fix the problem, since `@vercel/edge-config` currently relies on it.

I think our only options are to make it a normal dependency and bundle it with the rest, OR find a way to make the import optional at runtime based on whether that package exists.

**Comment by alvis** [comment]
As long as `@opentelemetry/api` is explicitly imported, `@opentelemetry/api` cannot be marked as optional. It will break!
To make it truly optional, use dynamic import

https://github.com/vercel/storage/blob/979932e83cc8a1aa5b775eae6131884f684bdbf5/packages/edge-config/src/utils/tracing.ts#L1-L5

**Comment by AndyBitz** [comment]
> As long as `@opentelemetry/api` is explicitly imported, `@opentelemetry/api` cannot be marked as optional. It will break! To make it truly optional, use dynamic import
> 
> https://github.com/vercel/storage/blob/979932e83cc8a1aa5b775eae6131884f684bdbf5/packages/edge-config/src/utils/tracing.ts#L1-L5

@alvis that's correct. However, `import()` won't work when used as part of the Edge Runtime. It would also require a separate init function or Top-Level Await in our case.

We might opt for exposing a `setTracer` function so that everyone can set it themselves without the `@vercel/edge-config` package relying on `'@opentelemetry/api` directly. We'd then only import the types.

**Comment by AndyBitz** [comment]
@grikomsn I've tried the version from the following PR: https://github.com/vercel/storage/pull/620

It should make it completely optional now and avoid the error, but still provide a way to set the tracer through the `setTracerProvider` method.

If you want to try it yourself, we've published a pre-release version here: `1.1.0-69327daa-20240224143842`.

**Comment by AndyBitz** [comment]
We've just published `@vercel/edge-config` version `1.1.0` which exposes a `setTracerProvider` function to set the tracer explicitly making `@opentelemetry/api` completely optional, which should fix the build issue.

Thanks for reporting this! Let us know if anything else comes up.
