### ISSUE TITLE
[@vercel/postgres] - Error: syntax error at or near "$1"

### ISSUE THREAD

**Issue by sanchezgaviermatias** [vercel/storage#619]
When trying to use Vercel Postgres, I have an error with string interpolation.

```
let table= "my_table";
const { rows, fields } = await sql`SELECT * FROM ${table}  limit 5;`;
```
I get this error:
```
 ⨯ node_modules\@neondatabase\serverless\index.js (1174:5) @ on.parseErrorMessage
 ⨯ error: syntax error at or near "$1"
    at WebSocket.emit (node:events:514:28)
    at Receiver.emit (node:events:514:28)
    at TLSSocket.emit (node:events:514:28)
```

**Comment by vvo** [comment]
Hey @sanchezgaviermatias, unfortunately, table names cannot be passed as query variables in PostgreSQL, just like column names. Only values can be used this way (example: `limit ${limit}`).

If you really need this, you can use createClient: https://vercel.com/docs/storage/vercel-postgres/sdk#createclient and access the query method: https://node-postgres.com/apis/client#clientquery. So that you can have a dynamic table name (JS based) and use SQL templating for everything else (values, via "Parameterized query").

Good luck!

**Comment by phillipc421** [comment]
Quick note, node-postgres **does not support** parameterized identifies because Postgres itself does not support this natively.

[From their docs: ](https://node-postgres.com/features/queries#parameterized-query)

"PostgreSQL does not support parameters for identifiers. If you need to have dynamic database, schema, table, or column names (e.g. in DDL statements) use [pg-format](https://www.npmjs.com/package/pg-format) package for handling escaping these values to ensure you do not have SQL injection!"

Have to use another package :/
