### ISSUE TITLE
CORS error when used on client side

### ISSUE THREAD

**Issue by HassenHichri** [vercel/storage#70]
Hi,
I'm trying to use edge config on the client side in a NextJS app but i'm getting CORS errors
<img width="712" alt="Screenshot 2023-03-01 at 11 03 57" src="https://user-images.githubusercontent.com/10193983/222113719-085c9b78-fd62-431e-987d-6c6195901c3e.png">

**How to reproduce**
just call `get` or `getAll` method in the browser
```javascript
import { getAll } from '@vercel/edge-config';
import { useEffect } from 'react';

const MyPage = () => {
  useEffect(() => {
    console.log(process.env.EDGE_CONFIG);
    getAll().then((result) => {
      console.log(result);
    });
  }, []);
  return <div>MyPage</div>;
};

export default MyPage;
```

**Environment**
Chrome Version 110.0.5481.177 (Official Build) (arm64)
MacOS 13.2.1

**Comment by dferber90** [comment]
The error here is that `process.env.EDGE_CONFIG` environment variable will not be defined in the browser, so the `@vercel/edge-config` SDK will not know where to send those requests to.

Reading Edge Config from the client is technically possible by using the following approach, but it comes with critical tradeoffs as you need to purposefully leak your Edge Config read-access token giving anyone access to read the whole contents of your Edge Config.

I've previously written about this here: https://github.com/orgs/vercel/discussions/1542#discussioncomment-4984365


_Apologies for the late reply, I just realized my notifications were configured incorrectly._

**Comment by HassenHichri** [comment]
@dferber90 no worries. I'm not sure it's the case here, I exposed `EDGE_CONFIG` env variable to the client, if that was the case the connection string would be `undefined`, right? 🤔

**Comment by dferber90** [comment]
Oh, I just noticed that you blacked parts out in the screenshot.  The "It does not have HTTP ok status." message of your screenshot makes me think you might be sending an outdated token.

**Comment by BasavarajPatil24** [comment]
### Subject: CORS Issue in Next.js Edge Configuration SDK Implementation



Hello,
I am encountering a CORS (Cross-Origin Resource Sharing) issue while using the Next.js Edge Configuration SDK. The issue arises when attempting to make requests to the Edge Configuration API from my Next.js application using SDK.


### Code Implementation: 
`/frontend/repositories/blog/adapters/edgeConfigAdapter.ts`
```
import { createClient, EdgeConfigClient } from '@vercel/edge-config';
import { UpdateEdgeConfigItem } from '../types';
import axios, { Method } from 'axios';

export class VercelEdgeConfig {
  private client: EdgeConfigClient;

  constructor() {
    this.client = createClient(
      `https://edge-config.vercel.com/${edgeStoreId}?token=${token}`,
    );
  }

  async readEdgeConfig(key: string) {
    return await this.client.get(key);
  }

  async updateEdgeConfig(items: UpdateEdgeConfigItem): Promise<Record<string, unknown>> {
    try {
      const config = {
        method: 'PATCH' as Method,
        url: `https://api.vercel.com/v1/edge-config/${edgeStoreId}/items?teamId=${teamId}`,
        headers: {
          Authorization: `Bearer ${API_TOKEN}`,
          'Content-Type': 'application/json',
        },
        data: items,
      };

      const response = await axios.request(config);
      return response.data;
    } catch (error) {
      throw new Error(`UpdateEdgeConfig failed. ${error}`);
    }
  }
}

```
`frontend/Blog/lib/client/add-wishlist-item.ts`
```
import { VercelEdgeConfig } from 'repositories/blog/adapters/edgeConfigAdapter';

// helper function
const getStoreId = async (key: string) => {
  const vercelClient = new VercelEdgeConfig();
 count storeValue = vercelClient.readEdgeConfig(key)
  return storeValue || '';
};

const value = await getStoreId(blogId);
```

### Description of the Issue:
I have encountered a CORS issue when attempting to access the `get` method provided by the Vercel Edge Configuration SDK. Although I have created an object with `get` and `patch` methods for the Vercel Edge Network, I face this problem specifically when calling the `readEdgeConfig` method to read the edge configuration value(SDK method). Interestingly, I do not experience this issue when using Axios or fetching the value through REST API methods. Consequently, I have successfully utilized the `updateEdgeConfig` function since it employs the REST API method but I have the request limitations with REST API interns of number of calls per second. So how to use SDK functions and solve the CORS issue.

### Expected Behavior:
I expect to be able to utilize the SDK implementation for Edge Configuration in my Next.js application without experiencing any CORS errors. The requests originating from the localhost (http://localhost:3000) should be permitted.

**Comment by AAorris** [comment]
Hey @Banou26! You had the right hunch here.

OPTIONS requests were returning a 404 and this caused CORS preflights to fail.

We've made some updates, and they'll take effect the next time you save changes to your Edge Config. After updating, can you try the same kind of request (without `credentials: include`) and ensure that things are working as you'd expect?

Likewise @BasavarajPatil24, I believe you can test against the code you showed above after saving an update to your Edge Config.

Thanks!
